# Generated by Django 3.2.7 on 2021-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_jobs_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
