version: '3.3'

services:

  nginx:
    build: .
    image: umputun/nginx-le:v1.4.2
    volumes:
      - .:/code
      - ./docker/nginx/testgr.conf:/etc/nginx/conf.d/testgr.conf
    restart: always
    ports:
      - "80:80"
    environment:
     - LETSENCRYPT=false

  web:
    volumes:
      - .:/code
    build:
      context: ./docker/web/
      dockerfile: ./Dockerfile
    command: >
        bash -c "python manage.py migrate
        && gunicorn testgr.wsgi --bind 0.0.0.0:8000
        & daphne testgr.asgi:application -p 9000 -b 0.0.0.0
        & celery -A testgr worker --loglevel INFO
        & celery -A testgr beat -l INFO"
    env_file:
      - config.env
    depends_on:
      - redis

  redis:
    build: ./docker/redis
    depends_on:
      - nginx
