version: '3.3'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changeonprod
    depends_on:
     - migration
  migration:
    volumes:
      - .:/code
    build: .
    environment:
      - SECRET_KEY=changeonprod
    command: python /code/manage.py migrate
    depends_on: 
     - make_migrations
  make_migrations:
    volumes:
      - .:/code
    build: .
    environment:
      - SECRET_KEY=changeonprod
    command: python /code/manage.py makemigrations
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"


