version: '3.3'

services:

  nginx:
    volumes:
      - .:/code
    build: ./docker/nginx/
    restart: always
    ports:
      - "80:80"

  web:
    volumes:
      - .:/code
    build:
      context: ./docker/web/
      dockerfile: ./Dockerfile
    command: ["bash", "-c", "python manage.py migrate && gunicorn testgr.wsgi --bind 0.0.0.0:8000"]
    env_file:
      - config.env
    depends_on:
      - nginx

  redis:
    build: ./docker/redis
    depends_on:
      - web

  websocket:
    volumes:
      - .:/code
    build:
      context: ./docker/web/
      dockerfile: ./Dockerfile
    command: daphne testgr.asgi:application -p 9000 -b 0.0.0.0
    depends_on:
      - redis
    env_file:
      - config.env
