# Generated by Django 2.1.4 on 2019-01-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('remapped_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('fw_type', models.SmallIntegerField(blank=True, null=True)),
                ('tests_passed', models.SmallIntegerField(blank=True, null=True)),
                ('tests_failed', models.SmallIntegerField(blank=True, null=True)),
                ('tests_skipped', models.SmallIntegerField(blank=True, null=True)),
                ('tests_aborted', models.SmallIntegerField(blank=True, null=True)),
                ('tests_not_started', models.SmallIntegerField(blank=True, null=True)),
                ('tests_in_progress', models.SmallIntegerField(blank=True, null=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='loader.Environments')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('msg', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='loader.TestJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TestsStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
                ('fw_type', models.SmallIntegerField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('time_taken2', models.DurationField(blank=True, null=True)),
                ('time_taken3', models.DurationField(blank=True, null=True)),
                ('calculated_eta', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_storage', to='loader.TestsStorage'),
        ),
    ]
