# Generated by Django 2.1.1 on 2018-09-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('stop_time', models.FloatField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('env', models.TextField(blank=True, null=True)),
                ('tests_success', models.IntegerField(blank=True, null=True)),
                ('tests_errors', models.IntegerField(blank=True, null=True)),
                ('tests_failed', models.IntegerField(blank=True, null=True)),
                ('tests_skipped', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('identity', models.TextField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('stop_time', models.FloatField(blank=True, null=True)),
                ('_time_taken', models.FloatField(blank=True, db_column='time_taken', null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('msg', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='loader.TestJobs')),
            ],
        ),
    ]
