# Generated by Django 2.2.1 on 2019-07-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjobs',
            name='uuid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tests',
            name='uuid',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='testsstorage',
            name='identity',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
