# Generated by Django 2.2.1 on 2019-07-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_auto_20190731_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsstorage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
