# Generated by Django 3.0.3 on 2020-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_testsstorage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjobs',
            name='custom_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
