# Generated by Django 3.0.5 on 2020-04-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0007_testsstorage_suppress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='type',
        ),
    ]
