# Generated by Django 3.1.4 on 2020-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0011_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshots',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
    ]
