# Generated by Django 3.1.7 on 2021-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0012_screenshots_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjobs',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
