# Generated by Django 3.2.7 on 2021-09-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0014_auto_20210830_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testjobs',
            name='attachments',
        ),
        migrations.AddField(
            model_name='files',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='loader.testjobs'),
        ),
        migrations.AddField(
            model_name='files',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tests', to='loader.tests'),
        ),
    ]
